services:
  db:
    container_name: djangotreemenu-db
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=djangoTreeMenu
    restart: always
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - app:/data/djangotreemenu

  app:
    container_name: djangotreemenu-app
    build:
      context: .
      dockerfile: ./dockerfile
    depends_on:
      - db
    command: ["/app/scripts/dockerstart.sh"]
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - app:/data/djangotreemenu-app

networks:
  app-network:
    driver: bridge

volumes:
  app: